
language: cpp

os: linux
dist: trusty
sudo: false
compiler: gcc

addons:
  apt:
    packages:
      - libboost-dev
      - libboost-test-dev

script:
  - ./autogen.sh
  - ./configure --disable-static --enable-unity-build CXXFLAGS='-O1 -fprofile-arcs -ftest-coverage' LIBS='-lgcov'
  - make -j 2
  - ./test-suite/quantlib-test-suite --log_level=message -- --faster

after_success:
  - bash <(curl -s https://codecov.io/bash)

