
language: cpp

os: linux
dist: trusty
sudo: false
compiler: gcc

cache: ccache

addons:
  apt:
    packages:
      - libboost-dev
      - libboost-test-dev

script:
  - ./autogen.sh
  - ./configure --disable-static CXXFLAGS='-O2 -fprofile-arcs -ftest-coverage' LIBS='-lgcov'
  - ccache --zero-stats
  - ccache --max-size=2.5G
  - make -j 2 -C ql
  - ccache --show-stats

